services:
  nginx:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/ssl/private:ro
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8008:8008"
    volumes:
      - .:/api
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8008 --reload

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/api
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    command: uv run celery -A app.tasks worker --loglevel=info
