[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
oto = "otoUzj3eLyJXSkB4DmfGR63eHBMQ9tqPHJaGX8ySSsY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/ext_program/metaplex.so"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/ext_program/core.so"